services:
  app:
    image: php:8.1-cli
    container_name: api_escaperoom_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - mysql
    networks:
      - backend
    command: tail -f /dev/null

  mysql:
    image: mysql:8.0
    container_name: api_escaperoom_mysql
    restart: always
    environment:
      MYSQL_DATABASE: api_escaperoom
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend
volumes:
  mysql-data:

networks:
  backend:
    driver: bridge